# Generated by Django 3.0.8 on 2020-07-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentacion',
            options={'verbose_name_plural': 'Presentaciones'},
        ),
    ]
