# Generated by Django 3.0.8 on 2020-07-28 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('ArtCod', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código del artículo')),
                ('ArtNom', models.CharField(max_length=30, verbose_name='Nombre')),
                ('ArtDes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('ArtImg', models.ImageField(blank=True, null=True, upload_to='pics/articles', verbose_name='Imagen')),
                ('ArtCosUni', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo unitario')),
                ('ArtSitAct', models.BooleanField(default=True, verbose_name='Disponible')),
                ('ArtSto', models.IntegerField(default=1, verbose_name='Cantidad en stock')),
                ('ArtCatCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
            ],
        ),
    ]
