# Generated by Django 3.0.8 on 2020-07-30 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
        ('presentaciones', '0002_auto_20200729_2209'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IngDetCan', models.IntegerField(verbose_name='Cantidad')),
                ('IngDetCosUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('IngDetArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
                ('IngDetCabCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.Ingreso_Cabecera')),
                ('IngDetPreCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.Presentacion')),
            ],
        ),
    ]
