# Generated by Django 3.0.8 on 2020-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
        ('articulos', '0002_ingreso_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ArtIngDet',
            field=models.ManyToManyField(through='articulos.Ingreso_Detalle', to='ingresos.Ingreso_Cabecera'),
        ),
    ]
