# Generated by Django 3.0.7 on 2020-08-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20200729_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='ArtCosUni',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Costo unitario'),
        ),
    ]
