# Generated by Django 3.0.8 on 2020-08-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
        ('presentaciones', '0002_auto_20200729_2209'),
        ('articulos', '0004_auto_20200729_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso_detalle',
            options={'verbose_name_plural': 'Detalle de ingresos de productos'},
        ),
        migrations.AlterField(
            model_name='ingreso_detalle',
            name='IngDetArtCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo', verbose_name='Artículo ingresado'),
        ),
        migrations.AlterField(
            model_name='ingreso_detalle',
            name='IngDetCabCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.Ingreso_Cabecera', verbose_name='Código de documento de ingreso'),
        ),
        migrations.AlterField(
            model_name='ingreso_detalle',
            name='IngDetPreCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.Presentacion', verbose_name='Presentación del artículo'),
        ),
        migrations.AlterUniqueTogether(
            name='ingreso_detalle',
            unique_together={('IngDetCabCod', 'IngDetArtCod')},
        ),
    ]
