# Generated by Django 3.0.8 on 2020-08-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0003_delete_salida_detalle'),
        ('categorias', '0001_initial'),
        ('presentaciones', '0002_auto_20200729_2209'),
        ('articulos', '0005_auto_20200806_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='ArtCatCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='salida_detalle',
            name='SalDetArtCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='salida_detalle',
            name='SalDetCabCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salidas.Salida_Cabecera', verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='salida_detalle',
            name='SalDetPreCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.Presentacion', verbose_name='Unidad de medida'),
        ),
    ]
