# Generated by Django 3.0.7 on 2020-08-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20200807_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='ArtCosUni',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Costo unitario'),
        ),
    ]
