# Generated by Django 3.0.7 on 2020-08-08 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('articulos', '0006_auto_20200807_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='ArtCatCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria'),
        ),
    ]
