# Generated by Django 3.0.8 on 2020-08-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_auto_20200806_1230'),
        ('articulos', '0008_auto_20200807_2322'),
    ]

    operations = [
    ]
