# Generated by Django 3.0.8 on 2020-07-30 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0002_auto_20200729_2209'),
        ('articulos', '0003_articulo_artingdet'),
        ('salidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salida_cabecera',
            options={'verbose_name_plural': 'Salidas de productos'},
        ),
        migrations.CreateModel(
            name='Salida_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalDetCosUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('SalDetCan', models.IntegerField(verbose_name='Cantidad')),
                ('SalDetArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
                ('SalDetCabCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salidas.Salida_Cabecera')),
                ('SalDetPreCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.Presentacion')),
            ],
            options={
                'verbose_name_plural': 'Detalles de salida de productos',
                'unique_together': {('SalDetCabCod', 'SalDetArtCod')},
            },
        ),
    ]
