# Generated by Django 3.0.8 on 2020-07-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0002_auto_20200729_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salida_Detalle',
        ),
    ]
