# Generated by Django 3.0.8 on 2020-07-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('TraNomUsu', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre de usuario')),
                ('TraNom', models.CharField(max_length=50, verbose_name='Nombre de pila')),
                ('TraApe', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('TraSex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo del trabajador')),
                ('TraFecNac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('TraDNI', models.CharField(max_length=15, verbose_name='DNI')),
                ('TraTel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de contacto')),
                ('TraEma', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico')),
                ('TraAcc', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('TraPas', models.CharField(max_length=20, verbose_name='Password')),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
    ]
