# Generated by Django 3.0.8 on 2020-08-11 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='TraAcc',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='TraApe',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='TraEma',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='TraNom',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='TraPas',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='TraDNI',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='TraFecNac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='TraNomUsu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='TraSex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True, verbose_name='Sexo del trabajador'),
        ),
    ]
