# Generated by Django 3.0.8 on 2020-07-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('CatCod', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código de categoría')),
                ('CatDes', models.CharField(max_length=30, verbose_name='Descripción')),
                ('CatImg', models.ImageField(blank=True, null=True, upload_to='pics/categories', verbose_name='Imagen')),
            ],
        ),
    ]
