# Generated by Django 3.0.8 on 2020-07-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ProCod', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='RUC del proveedor')),
                ('ProNom', models.CharField(max_length=50, verbose_name='Nombre del proveedor')),
                ('ProDir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('ProTel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
