# Generated by Django 3.0.8 on 2020-07-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ProDir',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ProNom',
            field=models.CharField(max_length=200, verbose_name='Nombre del proveedor'),
        ),
    ]
